services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - POSTGRES_DB=foringdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_foring_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=foringdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_foring_data:
